spring.application.name=smart-space-backend
spring.threads.virtual.enabled=false
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.defaults.enabled=true

## Configura��es de Conex�o com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_space_db
#spring.datasource.url=jdbc:postgresql://localhost:5433/smart-space-booking
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��es do Hibernate (JPA)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
server.servlet.context-path=/api

# CORS
cors.allowed.origins=http://localhost:5173

# Files
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
file.upload-path=/files

spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Fortaleza

# Gemini
gemini.api.key=SUA-CHAVE-AQUI
gemini.api.url=https://generativelanguage.googleapis.com
gemini.model=gemini-2.5-flash

# MS de Mídia
media.server.url=http://localhost:8088/api/file-server/v1/files